name: syncToGitee # 工作流名称
# on.<event_name>.types 定义将触发工作流运行的事件活动类型。
on: # 指定工作流的触发事件
  push: # 用户push时触发工作流
    branches: # 代码提交的分支,只有提交到该分支时才触发工作流
      - gh-pages
jobs: # 任务是在同一个运行器上执行的一组步骤（steps）
  repo-sync: # 定义了一个名为 repo-sync 的任务
    runs-on: ubuntu-latest # 配置任务运行在最新的 Ubuntu Linux 运行器。
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with: # with 下 时 uses 动作执行需要的参数
          src: "github/SKYE-iiii"
          dst: "gitee/nice_995"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "Blog" #表示单一仓库同步
          force_update: true #为 true 表示启用 git push -f 强制同步
          debug: true #为 true 表示启用 debug 开关，会显示所有执行命令

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: nice_995
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: nice_995/Blog
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
